name: annabell

services:
  app:
    image: dataset:${ANNABELL_VERSION}
    build:
      context: .
      target: final
      args:
        - ANNABELL_VERSION=${ANNABELL_VERSION}
    volumes:
      - ./shared_data:/app/data:rw
    stdin_open: true
    tty: true